name: Feature Request
description: Request something to be added to the engine
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on **Xythe** engine?
    validations:
      required: true
